# Generated by Django 5.1.1 on 2024-09-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
